### ISSUE TITLE
BGP authentication

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#11]
We don't expose any authentication parameter such as key/secrets, although this is mandated by SPs. These parameters may be peer-specific, so it looks like a good idea to expose these in the bgp peer + peer-group.

(For now) we should also focus on exchanging keys/secrets and be agnostic of which authentication is used (legacy md5 2385 or recent/best practice rfc5925).

**Comment by boucadair** [comment]
A proposal was covered in [ffff499](https://github.com/boucadair/attachment-circuit-model/commit/ffff49949ab219edb47823e9a163bd465062afb4)
