### ISSUE TITLE
Can we make BGP peer addresseses as optional ?

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#12]
Hi,

can we make ALL BGP peer addresseses as optional (so far only ro local-address is optional) ?
The default would be to rely on ip-connection parameters when unambigous.

**Comment by boucadair** [comment]
Fxied now with [0897004](https://github.com/boucadair/attachment-circuit-model/commit/0897004cd5e34d989157b505c5454a0512ac63f9)
