### ISSUE TITLE
discuss the case of multiple CE reachable over a same AC

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#17]
We may have multiple CE sitting on a same AC (e.g. the AC is the attachment to an L2VPN behind which we have multiple CEs).
We can identify each CE with a dedicated peer-sap.

If we want to manage the ip/routing configuration for a given CE,  the model seems not handy, because of the ac->sap binding. Indeed, we need to define several ACs/SAP  so we can attach the adequate ip/routing config. However, technically this is the same AC !

Should we have an intermediate level in the hierarchy ?
Should we come up with child/parent acs ?
Should change the definition of ac to something more generic (ac being one application) ?

This is definitely worth some discussion, so I am logging the issue.

**Comment by robric** [comment]
Adding thought - should we clarify the concept of  multipoint ACs ?
We can have multiple L3 CEs aggregated on a single Switch which connects to the Network.
Technically, having a single L2 AC and multiple L3 AC... Or we're having  a point-to-multipoint AC.

**Comment by boucadair** [comment]
@robric, I wonder whether this is fixed with the ac-bundle as well?
