### ISSUE TITLE
Have a more generic way to capture failure detection than BFD  ?

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#203]
BFD is technology specific and we might have alternative failover detection mechanism.

Should not we express the fact that fast detection is wanted for an Endpoint in a non technology specific (oam protected). This would refer to the profile name which capture the technology-specific part.

We could for example list a set of endpoint for which we want protection, no matter what protocol leverages it: static Next Hop or BGP neighbor.

**Comment by boucadair** [comment]
@boucadair, check the bfd to be indexed per session. This will be consistent with act-ntw

**Comment by boucadair** [comment]
@boucadair: change to failure-detection-profile

**Comment by boucadair** [comment]
went with local/remote @ for the ac-svc, but kept so far the current names to be consistent with RFC9127

**Comment by boucadair** [comment]
Fixed with #213 and #215
