### ISSUE TITLE
Inter AS option support

### ISSUE THREAD

**Issue by billwuqin** [boucadair/attachment-circuit-model#22]
To support multidomain connectivity stitching, should inter AS option be supported? e.g., Option A, Option B, Option C. Is there control pane or data plane parameters that need to be specified? Or These details should be hided or not exposed to the upper layer?

**Comment by boucadair** [comment]
Like #23, the internal structure of the service that involve ACes does not matter for the service-ac model. It is, however, meaningful for the network-ac (which is an augmentation of the SAP) as network-to-network ACs will be needed for some options and those are visible to the network controller.
