### ISSUE TITLE
bad type for static route in acs-for-slices.json example

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#25]
line 34 shows bgp as the type, while this static.
[acs-for-slices.json](https://github.com/boucadair/attachment-circuit-model/blob/main/json-examples/acs-for-slices.json)

        "routing-protocols": {
          "routing-protocol": [1
            {
              "id": "1",
    ===> "type": "ietf-vpn-common:bgp-routing",
              "static": {

**Comment by boucadair** [comment]
Thanks, Richard. Fixed [0ab4a16](https://github.com/boucadair/attachment-circuit-model/commit/0ab4a169c1045b1f4e224da2c6b96fb94511bd85)
