### ISSUE TITLE
Link back to the 3GPP NRM ObjectClass EP_transport 

### ISSUE THREAD

**Issue by Ivan-Bykov-RBBN** [boucadair/attachment-circuit-model#33]
We are pushing confederated data model approach in CR for 3GPP NRM TS28.541. The idea is to have a ProxyClass NextHopInfo to hold Transport Network EPE-related information. 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/114131776/218749134-154e382d-c963-49bc-83fc-9870cdfe19e1.png">
Once this would be in place, the link back to the relevant NRM ObjectClass on 3GPP/ORAN subsystem e.g. EP_Transport is expected in order to navigate and to verify.

**Comment by Ivan-Bykov-RBBN** [comment]
3GPP SA5 folks anticipated the expectation of the link back no NRM. 
My feeling is that the simple link to the 3GPP NRM MIB tree of EP_Transport will do the job, so a little impact of "infrastructure" AC model is expected.

**Comment by boucadair** [comment]
@Ivan-Bykov-RBBN, please provide an example to illustrate how this can be used. Thanks.
