### ISSUE TITLE
Link or a reference of nbi-yang service id(s), which are utilizing attachment-circuit-model  "infrastructure" 

### ISSUE THREAD

**Issue by Ivan-Bykov-RBBN** [boucadair/attachment-circuit-model#35]

**Comment by boucadair** [comment]
FWIW: 
* We plan to have an ac-ref under the service itself. See the ac-glue module in the draft.

* We do also have access to a similar information at the network level: https://datatracker.ietf.org/doc/draft-boro-opsawg-ntw-attachment-circuit/

>      augment /nw:networks/nw:network/nw:node/**sap:service/sap:sap**:
>        +--rw ac* [name]
>           +--rw name                 string
>           **+--rw ac-ref?              ac-svc:attachment-circuit-reference**
>           +--rw ac-profile* [profile-id]
>           |  +--rw profile-id    -> /nw:networks/network/ac-profile/name
>           +--rw description?         string
>           +--rw l2-connection
>           |  ...
>           +--rw ip-connection
>           |  ...
>           +--rw routing-protocols
>           |  ...
>           +--rw oam
>           |  ...
>           +--rw security
>              ...

Note that a SAP is defined as follows:

              +--rw service* [service-type]
                 **+--rw service-type                   identityref
                 +--rw sap* [sap-id]**
                    +--rw sap-id                      string
                 ...

the "service-type" can be set to l3vpn, l2vpn, vpn+, network-slice, vxlan, evpn, etc. 

I guess you want a read-only data node to also expose the service-types to the customer/application in the service model. Can you please elaborate what would be the typical usage? Thanks.
