### ISSUE TITLE
discuss VRRP

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#46]
Listing here a few concerns regarding vrrp:
- technology specific (at the end of the day customer wants to consume a virtual IP NH/Gateway).
- is virtual ip is enough for a service model ? 
- VRRP is dependant of the subnet wherin in the VIP  lies -> we can have several VRRP in case of secondary addresses. Here vrrp is in routing-protocols => not the right placehold imho
-  a good point in current vrrp is the admin/op status => maybe we could move these under the virtual-ip that can be a good indication for service monotiroing.

**Comment by boucadair** [comment]
As discussed in the past, I prefer to leave the current structure to ease mapping with existing LxNMs.
