### ISSUE TITLE
Review Section 3 (Use Cases)

### ISSUE THREAD

**Issue by boucadair** [boucadair/attachment-circuit-model#49]

**Comment by vlopezalvarez** [comment]
Comments provided in https://github.com/boucadair/attachment-circuit-model/commit/fe9b8e92741e94675ab8560096d724ddb36278a1

**Comment by boucadair** [comment]
Thanks @vlopezalvarez. Can you please push this as a PR? Thanks.

**Comment by boucadair** [comment]
Done: https://github.com/boucadair/attachment-circuit-model/pull/79
