### ISSUE TITLE
deal with multiple local subnets (local-address) - ip-connection list ?

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#6]
This case is an exception since most deployment rely on a single subnet per ac/logical link (best practice). However, it mandated by some deployments (example migration or legacy design).

**Comment by boucadair** [comment]
For ac-ntw model, I think that having two ACs would be just fine to handle migration/merging cases. The ac-ref data node can help correlating ACs that are pointing to a single (service) AC.
```
  augment /nw:networks/nw:network/nw:node/sap:service/sap:sap:
    +--rw ac* [name]
       +--rw name                 string
       +--rw ac-ref?              ac-svc:attachment-circuit-reference
```

We may add some text to explain this.
