### ISSUE TITLE
should we add a contraint on bearer to identify the SP POP to which the bearer is attached ?

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#60]

**Comment by robric** [comment]
The idea is to have the possibility to bind bearer (or get available bearers) with a given SP POP. This assumes that customer gets the inventory (partial or full) of POPs.
![image](https://github.com/boucadair/attachment-circuit-model/assets/21667569/cef4a3c3-b42c-4f7d-9117-d00c3e5dc241)

**Comment by robric** [comment]
Med's proposal: re-use "placement constraints" in bearer as well

**Comment by boucadair** [comment]
Explicit selection of a PoP is not that used by conventional providers. Need more discussion whether this choice is included in the base AC model.

Designing constraints as a choice allows to augment the models if such explicit id is to be supplied.

**Comment by boucadair** [comment]
Please review https://github.com/boucadair/attachment-circuit-model/pull/80
