### ISSUE TITLE
Discuss examples A.6 and A.7 are arguable.

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#65]
I would like to discuss these examples since I see duplicate IPs for each acs.
That's rather confusing.

Additionally I don't see any attachment point such as bearer or peer-sap.

**Comment by boucadair** [comment]
Duplicate IP addresses are normal for these examples. The aim of these examples is to illustrate how profiles are useful to factorize data, and thus help to have more compact data.

**Comment by boucadair** [comment]
Agree reference-bearer or peer-sap needed to be added to the JSON examples. Will take care of that. Thanks @robric for catching this.

**Comment by robric** [comment]
Hi Med, I get the intention of factorizing data, however this is from my perspective an unfortunate choice.
Duplicate IP is very bad practice, so we should find other examples.

**Comment by boucadair** [comment]
#66 is an attempt to restructure the examples. Updated the text to also mention that the example with redundant data is not recommended. 

If there are other example of duplicate data that can be made compact by the use of one or more profiles, @robric feel free to propose them. Thanks.
