### ISSUE TITLE
Use case for MPLS/SRv6  as an AC

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#67]
MPLS as data plane can be linked to multiple types of  control planes for label assignements.
Discuss whether we should support both static and dynamic Label assignment should be considered.
- Static should be straightforward, although this is likely a minor Use Case. Dynamic is more important.
- Dynamic: 
  1 L3VPN: Key identifiers are RD and RTs. 
  2 EVPN / EVPN-VPWS ?
1 looks more important imho.

**Comment by boucadair** [comment]
Ok with the use case with the intent to limit to a minimum set of info (RTs, typically).
@vlopezalvarez to review.

**Comment by robric** [comment]
Since this is a more complex Use Case, it is proposed to delay this Issue for later. The objective of a first iteration is to describe more common and popular use cases (e.g. vlan-id).

**Comment by boucadair** [comment]
> RTs, typically

@robric, can you please check what changes are needed to support RTs.

@vlopezalvarez, did you had a chance to review? Thanks.

**Comment by boucadair** [comment]
@robric to identify the set of required modifications and then based on the amount of changes, decide whether to include it in scope or in a separate I-D.
