### ISSUE TITLE
Add metric to static routes (for primary/backup logic propagation)

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#7]
We should keep metric for static routes 
We can ignore preference for now since it is related to route selection between protocols, so this is more a related to how the global service is defined (templatised).

**Comment by boucadair** [comment]
Agree.  This is now fixed as per [b0231c6](https://github.com/boucadair/attachment-circuit-model/commit/b0231c6eae0139d19b36d3f69baca291d7b20e6b)
