### ISSUE TITLE
BGP container review: Add soft-reconfiguration to BGP

### ISSUE THREAD

**Issue by oscargdd** [boucadair/attachment-circuit-model#77]
Include soft-reconfiguration  (RFC 2918) in the bgp container. When doing BGP peering is it sometimes required to determine the type of behavior.

**Comment by boucadair** [comment]
@oscargdd, can you please propose a PR for this one?

**Comment by boucadair** [comment]
@oscargdd, please see #168 which I think addresses this issue in a more generic manner.
