### ISSUE TITLE
oper-status

### ISSUE THREAD

**Issue by boucadair** [boucadair/attachment-circuit-model#84]
The main doubt we have received so far and “hot” topic is the oper-status management. 

•	How the oper-status should be used in service and node level. 
•	How are related if there are several vpn-nodes available. 
•	How node changes should be reflected in the whole service oper-status.

Here I have heard several options (combinations) and the implementations are following different patterns. 
So clarify the expected behavior its really necessary for the multivendor scenarios.

**Comment by boucadair** [comment]
@sbarguil, I think this can be clarified in https://datatracker.ietf.org/doc/draft-boro-opsawg-ntw-attachment-circuit/. We do already have a good discussion on status in rfc9408 that we can further elaborate in the ntw-attachment.

See also https://mailarchive.ietf.org/arch/msg/opsawg/NpLJPSFIljA3rGHT4gmgAj2f8lE/

**Comment by sbarguil** [comment]
@Med and @oscargdd, do we have any suggested behavior for the default values in the Network model. I mean, for example BFD has some default configuration values:

![image](https://github.com/boucadair/attachment-circuit-model/assets/13772485/c0be954b-2699-4d8c-b51c-66f756ec915d)

If a get request is send to the controller asking for the Net-Accss details, the restconf server can report the 'default-values' unless the 'with-default-values' & trim option  is supported. 

Hence, if the controller reports the all values including default values:  

- Those values mean the controller send it to the network? 
- How we can diferentiate between what was send to the network and what is default?

**Comment by boucadair** [comment]
Default handling can be controlled as depicted below: 

![image](https://github.com/boucadair/attachment-circuit-model/assets/15671127/b999ca74-1a70-456d-90f7-5843dfa2296b)

and
![image](https://github.com/boucadair/attachment-circuit-model/assets/15671127/acf4ea71-b883-4440-be1a-32526e0e6329)

There might be cases where the server supports default values that are not aligned with the spec. The client should at least retrieve these values and compare them with its interpretation once. Then, it can set the trim/explicit filters to control which data to be reported by a server.

Data nodes that are not reported in the explicit mode but was reported with report-all are those that include a default value not explicitly set by the network.
