### ISSUE TITLE
Bearer: add provider parameters

### ISSUE THREAD

**Issue by boucadair** [boucadair/attachment-circuit-model#86]
From @Ivan-Bykov-RBBN (https://github.com/boucadair/network-attachment-circuits/issues/7):

PE parameters in bearer ( inherited from 3GPP TS28.541 where is mentioned PE paramenters NextHopInfo)
+--rw provider-point
add provider port id
| +--rw device
| | +--rw device-id? string ---FQDN
add location of PE section

**Comment by Ivan-Bykov-RBBN** [comment]
Collapsed to a single comment
