### ISSUE TITLE
Should we have  local-as visible in BGP ?

### ISSUE THREAD

**Issue by robric** [boucadair/attachment-circuit-model#9]
Should we expose local-as in BGP. We have peer-as.
It is clear that the BGP AS for the backbone is usually well known, however we may simplify the provisionning by just exposing it as a RO object.

**Comment by boucadair** [comment]
Exposing this information is also useful for the customer to know which ASN to use to set up a session. Note that some mechanisms are currently being investigated to automatically discover a peer AS, but we don't need to require/discard such mechanisms to be in place. 

The leaf is set a read-only as can be seen at [a94a29d](https://github.com/boucadair/attachment-circuit-model/commit/a94a29d0e60baa91997d40982a80e49c331c44e9)
