### ISSUE TITLE
bearer issues 

### ISSUE THREAD

**Issue by Ivan-Bykov-RBBN** [boucadair/attachment-circuit-model#92]
1. There is a mismatch of 3GPP NRM TS-28.541 Clause  6.3.35 LogicalInterfaceInfo and bearer yang tree:
3GPP NRM: 
LogicalInterfaceInfo.portName? string
AC DM:
        no port info 

2. A mismatch of 3GPP NRM TS-28.623 Clause A 2.2.2 IOC ManagedElement and bearer yang tree:
3GPP NRM: 
        locationName? string 
AC DM:
        |  |  +--rw location
        |  |     +--rw location-name?  string

3. Missing parameters in bearer DM:

- crossing id and fiber parameters
- microwave line id with port id
- l2 or l3 leased service id
- id of additional switch in the middle, not controlled by "customer" or "provider"
- service may use more than one Bearer. It may be LAG, dual-homing, FHRP, EVPN - examples of L2/L3 services running on multiple bearers at the same time

**Comment by boucadair** [comment]
Point 3 is more related to the resources/network part of bearers. We don't have a network models for bearers. So, that's part is out of scope.

**Comment by boucadair** [comment]
Point (1) can be discussed in the teas applicability draft.

**Comment by boucadair** [comment]
Point (2) name mismatch can be clarified in the teas applicability spec.

**Comment by boucadair** [comment]
LAG is now covered in the new version
