### ISSUE TITLE
ietf-ac-ntw: Augmenting "node" instead of “sap” 

### ISSUE THREAD

**Issue by lana-wu** [boucadair/attachment-circuit-model#95]
This **ietf-ac-ntw** can be used for provisioning of ACs prior or during service provisioning.
For the two scenarios:
1. Before service provisioning, the SAP may not exist. Should the **AC list** be extended under "node" instead of "sap"?
2. During service provisioning, SAP is created with services, and AC list reference can added to "sap".

Suggested to change:
**OLD**
 augment /nw:networks/nw:network/nw:node/sap:service/sap:sap: 
       +--rw ac* [name]

**NEW**
 augment /nw:networks/nw:network/nw:node
       +--rw ac* [name]

 augment /nw:networks/nw:network/nw:node/sap:service/sap:sap: 
      +--rw ac-ref*

**Comment by boucadair** [comment]
@boucadair to add some text to explain the rationale of the current design. 

Then, revive the discussion to see of there is an issue to be fixed. 

Check if a controller can retrieve the set of available ACs for a given service.

**Comment by boucadair** [comment]
@lana-wu, please check #96.
